repos:
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.8.5
      hooks:
          - id: nbqa-black
          - id: nbqa-mypy
            args:
            - --ignore-missing-imports
            - --install-types
            - --non-interactive
          - id: nbqa-flake8
    - repo: https://github.com/kynan/nbstripout
      rev: 0.7.1
      hooks:
          - id: nbstripout
            args:
            - --drop-empty-cells
            - --extra-keys=cell.metadata.pycharm 
                metadata.vscode 
                metadata.celltoolbar
                metadata.kernelspec
                metadata.language_info.codemirror_mode.version
                metadata.language_info.pygments_lexer
                metadata.language_info.version
                metadata.toc
                metadata.notify_time
                metadata.varInspector
                cell.metadata.heading_collapsed
                cell.metadata.hidden
                cell.metadata.code_folding
                cell.metadata.tags
                cell.metadata.init_cell
